
const cfg=window.TPG_CONFIG;
const $=s=>document.querySelector(s);
let client=null, categories=[], menuItems=[], bookings=[], selectedFile=null;
let calendarDate=new Date(), selectedDate=null;

function configured(){return cfg.SUPABASE_URL.startsWith("https://")&&!cfg.SUPABASE_ANON_KEY.includes("PASTE_")}
function placeholder(label="Menu"){return "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="800"><rect width="100%" height="100%" fill="#173e2a"/><text x="50%" y="49%" text-anchor="middle" fill="white" font-family="Arial" font-size="34" font-weight="700">${String(label).replace(/[<>&"]/g,"")}</text><text x="50%" y="57%" text-anchor="middle" fill="#d8ad56" font-family="Arial" font-size="18">Image coming soon</text></svg>`)}

if(configured()){client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);$("#connectionInfo").textContent="เชื่อมต่อ Supabase configuration แล้ว"}
else{$("#loginStatus").textContent="กรุณาใส่ Publishable Key ใน config.js";$("#connectionInfo").textContent="ยังไม่ได้ใส่ Publishable Key"}

async function checkSession(){if(!client)return;const {data}=await client.auth.getSession();if(data.session)showDashboard(data.session.user)}
$("#loginButton").onclick=async()=>{if(!client)return;$("#loginStatus").textContent="กำลังเข้าสู่ระบบ...";const {data,error}=await client.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});if(error)$("#loginStatus").textContent=error.message;else showDashboard(data.user)}
async function showDashboard(user){$("#loginPanel").hidden=true;$("#dashboard").hidden=false;$("#logoutButton").hidden=false;$("#adminUser").textContent=user.email||"Admin";await Promise.all([loadCategories(),loadMenus(),loadBookings(),loadRestaurantSettings()])}
$("#logoutButton").onclick=async()=>{await client.auth.signOut();location.reload()}

document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===`panel-${b.dataset.tab}`));if(b.dataset.tab==="calendar")renderCalendar()})

async function loadCategories(){const {data,error}=await client.from("categories").select("*").order("sort_order");if(error)return alert(error.message);categories=data||[];$("#itemCategory").innerHTML="";$("#adminCategory").innerHTML='<option value="all">ทุกหมวด</option>';categories.forEach(c=>{$("#itemCategory").insertAdjacentHTML("beforeend",`<option value="${c.id}">${c.name_lo}</option>`);$("#adminCategory").insertAdjacentHTML("beforeend",`<option value="${c.id}">${c.name_lo}</option>`)})}
async function loadMenus(){const {data,error}=await client.from("menu_items").select("*,categories(name_lo)").order("sort_order");if(error)return alert(error.message);menuItems=data||[];renderMenus();updateStats()}
function filteredMenus(){const q=$("#adminSearch").value.trim().toLowerCase(),cat=$("#adminCategory").value,state=$("#adminAvailability").value;return menuItems.filter(i=>{const matchCat=cat==="all"||i.category_id===cat;const matchText=`${i.name_lo||""} ${i.name_th||""} ${i.name_en||""}`.toLowerCase().includes(q);const matchState=state==="all"||(state==="available"&&i.available)||(state==="unavailable"&&!i.available)||(state==="featured"&&i.featured);return matchCat&&matchText&&matchState})}
function renderMenus(){$("#adminMenuGrid").innerHTML="";filteredMenus().forEach(item=>{const card=document.createElement("article");card.className="admin-card";card.innerHTML=`<img alt="${item.name_lo}"><div class="admin-card-body"><h3>${item.name_lo}</h3><p>${item.categories?.name_lo||""} • ${Number(item.price).toLocaleString()} ກີບ</p><span class="availability ${item.available?"":"unavailable"}">${item.available?"มีขาย":"ปิดขาย"}</span> ${item.featured?'<span class="availability featured">แนะนำ</span>':""}<div class="admin-card-actions"><button class="edit">Edit</button><button class="delete">Delete</button></div></div>`;const img=card.querySelector("img");img.onerror=()=>{img.onerror=null;img.src=placeholder(item.name_lo)};img.src=item.image_url||placeholder(item.name_lo);card.querySelector(".edit").onclick=()=>startEdit(item);card.querySelector(".delete").onclick=()=>removeItem(item);$("#adminMenuGrid").appendChild(card)})}
function startEdit(i){$("#editId").value=i.id;$("#formTitle").textContent="แก้ไขเมนู";$("#itemNameLo").value=i.name_lo||"";$("#itemNameTh").value=i.name_th||"";$("#itemNameEn").value=i.name_en||"";$("#itemCategory").value=i.category_id;$("#itemPrice").value=i.price;$("#itemOrder").value=i.sort_order||999;$("#itemVariants").value=(i.variants||[]).join(" / ");$("#itemAvailable").checked=i.available;$("#itemFeatured").checked=i.featured;selectedFile=null;$("#imagePreview").hidden=!i.image_url;if(i.image_url)$("#imagePreview").src=i.image_url;window.scrollTo({top:0,behavior:"smooth"})}
function resetForm(){$("#menuForm").reset();$("#editId").value="";$("#formTitle").textContent="เพิ่มเมนูใหม่";$("#itemPrice").value=1000;$("#itemOrder").value=999;$("#itemAvailable").checked=true;selectedFile=null;$("#imagePreview").hidden=true}
$("#cancelEdit").onclick=resetForm;

const dz=$("#dropZone"),fileInput=$("#itemImage");
dz.onclick=()=>fileInput.click();
["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("dragover")}));
["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove("dragover")}));
dz.addEventListener("drop",e=>handleFile(e.dataTransfer.files[0]));
fileInput.onchange=e=>handleFile(e.target.files[0]);
function handleFile(file){if(!file)return;if(file.size>5*1024*1024)return alert("ไฟล์ต้องไม่เกิน 5 MB");if(!["image/jpeg","image/png","image/webp"].includes(file.type))return alert("รองรับ JPG, PNG และ WEBP");selectedFile=file;$("#imagePreview").src=URL.createObjectURL(file);$("#imagePreview").hidden=false}
async function uploadImage(file,itemId){if(!file)return null;const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`menus/${itemId}-${Date.now()}.${ext}`;const {error}=await client.storage.from(cfg.STORAGE_BUCKET).upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return {url:client.storage.from(cfg.STORAGE_BUCKET).getPublicUrl(path).data.publicUrl,path}}

$("#menuForm").onsubmit=async e=>{e.preventDefault();const editId=$("#editId").value,id=editId||crypto.randomUUID();const payload={name_lo:$("#itemNameLo").value.trim(),name_th:$("#itemNameTh").value.trim()||null,name_en:$("#itemNameEn").value.trim()||null,category_id:$("#itemCategory").value,price:Number($("#itemPrice").value),sort_order:Number($("#itemOrder").value),variants:$("#itemVariants").value.split("/").map(x=>x.trim()).filter(Boolean),available:$("#itemAvailable").checked,featured:$("#itemFeatured").checked};try{const image=await uploadImage(selectedFile,id);if(image){payload.image_url=image.url;payload.image_path=image.path}const query=editId?client.from("menu_items").update(payload).eq("id",editId):client.from("menu_items").insert({...payload,id});const {error}=await query;if(error)throw error;resetForm();await loadMenus();alert("บันทึกสำเร็จ")}catch(err){alert(err.message)}}
async function removeItem(item){if(!confirm(`ลบ ${item.name_lo}?`))return;const {error}=await client.from("menu_items").delete().eq("id",item.id);if(error)alert(error.message);else loadMenus()}
$("#adminSearch").oninput=renderMenus;$("#adminCategory").onchange=renderMenus;$("#adminAvailability").onchange=renderMenus;$("#refreshMenus").onclick=loadMenus;

async function loadBookings(){const {data,error}=await client.from("reservations").select("*").order("booking_date").order("booking_time");if(error)return console.error(error);bookings=data||[];renderBookings();renderCalendar();updateStats()}
function renderBookings(){const q=$("#bookingSearch").value.trim().toLowerCase();$("#bookingRows").innerHTML="";bookings.filter(b=>`${b.customer_name} ${b.phone}`.toLowerCase().includes(q)).forEach(b=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${b.booking_date}</td><td>${b.booking_time}</td><td>${b.customer_name}</td><td>${b.phone}</td><td>${b.guest_count}</td><td>${b.note||""}</td><td><select><option ${b.status==="new"?"selected":""}>new</option><option ${b.status==="confirmed"?"selected":""}>confirmed</option><option ${b.status==="cancelled"?"selected":""}>cancelled</option><option ${b.status==="completed"?"selected":""}>completed</option><option ${b.status==="no_show"?"selected":""}>no_show</option></select></td>`;tr.querySelector("select").onchange=async e=>{await client.from("reservations").update({status:e.target.value}).eq("id",b.id);loadBookings()};$("#bookingRows").appendChild(tr)})}
$("#bookingSearch").oninput=renderBookings;$("#refreshBookings").onclick=loadBookings;

function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function renderCalendar(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth();$("#calendarTitle").textContent=new Intl.DateTimeFormat("th-TH",{month:"long",year:"numeric"}).format(calendarDate);const first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());$("#calendarGrid").innerHTML="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),dayBookings=bookings.filter(b=>b.booking_date===key);const cell=document.createElement("div");cell.className=`calendar-day ${d.getMonth()!==month?"muted":""} ${selectedDate===key?"selected":""}`;cell.innerHTML=`<strong>${d.getDate()}</strong>${dayBookings.length?`<span class="booking-dot">${dayBookings.length} การจอง</span>`:""}`;cell.onclick=()=>{selectedDate=key;renderCalendar();renderDayBookings(key)};$("#calendarGrid").appendChild(cell)}}
function renderDayBookings(key){const list=bookings.filter(b=>b.booking_date===key);$("#dayBookings").innerHTML=`<h3>การจองวันที่ ${key}</h3>`+(list.length?list.map(b=>`<div class="day-booking"><strong>${b.booking_time} • ${b.customer_name}</strong><div>${b.guest_count} คน • ${b.phone} • ${b.status}</div><small>${b.note||""}</small></div>`).join(""):"<p>ยังไม่มีการจอง</p>")}
$("#prevMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};

async function loadRestaurantSettings(){
  try{
    const {data,error}=await client.from("restaurant_settings").select("*").eq("id",1).maybeSingle(); if(error)throw error;
    const row=data||{}; window.restaurantSettings=row;
    $("#vatModeSetting").value=row.vat_mode||"inclusive"; $("#vatRateSetting").value=Number(row.vat_rate??10);
    $("#settingNameLo").value=row.restaurant_name_lo||""; $("#settingNameTh").value=row.restaurant_name_th||""; $("#settingNameEn").value=row.restaurant_name_en||"";
    $("#defaultLanguageSetting").value=row.default_language||"lo"; $("#currencySetting").value=row.currency_code||"LAK";
    $("#themePrimarySetting").value=row.theme_primary||"#0b5d3b"; $("#themeAccentSetting").value=row.theme_accent||"#d8ad56";
    document.documentElement.style.setProperty('--primary',row.theme_primary||'#0b5d3b'); document.documentElement.style.setProperty('--accent',row.theme_accent||'#d8ad56');
    const {count}=await client.from('restaurant_tables').select('*',{count:'exact',head:true}).eq('active',true); $("#tableCountSetting").value=count||1;
    $("#settingsStatus").textContent="โหลดการตั้งค่าแล้ว";
  }catch(err){ $("#settingsStatus").textContent="กรุณารัน 02-UPGRADE-TO-V2.0.0.sql: "+err.message; }
}
async function setTableCount(target){
  const {data,error}=await client.from('restaurant_tables').select('*').order('table_number');if(error)throw error;let rows=data||[],active=rows.filter(x=>x.active);
  while(active.length<target){const inactive=rows.find(x=>!x.active);if(inactive){const {error:e}=await client.from('restaurant_tables').update({active:true,label:`ໂຕະ ${inactive.table_number}`}).eq('id',inactive.id);if(e)throw e;inactive.active=true;active.push(inactive)}else{const no=rows.reduce((m,x)=>Math.max(m,+x.table_number),0)+1;const {data:n,error:e}=await client.from('restaurant_tables').insert({table_number:no,label:`ໂຕະ ${no}`,capacity:4,active:true}).select().single();if(e)throw e;rows.push(n);active.push(n)}}
  while(active.length>target){const x=active.pop();const {error:e}=await client.from('restaurant_tables').update({active:false}).eq('id',x.id);if(e)throw e;}
}
$("#saveRestaurantSettings").onclick=async()=>{try{
  const payload={id:1,restaurant_name_lo:$("#settingNameLo").value.trim(),restaurant_name_th:$("#settingNameTh").value.trim(),restaurant_name_en:$("#settingNameEn").value.trim(),default_language:$("#defaultLanguageSetting").value,currency_code:$("#currencySetting").value,theme_primary:$("#themePrimarySetting").value,theme_accent:$("#themeAccentSetting").value,vat_mode:$("#vatModeSetting").value,vat_rate:Math.max(0,Number($("#vatRateSetting").value||0)),setup_completed:true,updated_at:new Date().toISOString()};
  $("#settingsStatus").textContent="กำลังบันทึก..."; const {error}=await client.from("restaurant_settings").upsert(payload,{onConflict:"id"});if(error)throw error;
  await setTableCount(Math.max(1,Math.min(500,Number($("#tableCountSetting").value)||1))); $("#settingsStatus").textContent="บันทึกสำเร็จ — เว็บไซต์และ POS ทุกเครื่องจะใช้ค่าใหม่"; await loadRestaurantSettings();
}catch(e){$("#settingsStatus").textContent=e.message}};
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#exportJson").onclick=()=>download(`menu-${new Date().toISOString().slice(0,10)}.json`,new Blob([JSON.stringify({version:'2.0.0',categories,menu_items:menuItems},null,2)],{type:'application/json'}));
$("#exportExcel").onclick=()=>{const rows=menuItems.map(i=>({name_lo:i.name_lo,name_th:i.name_th||'',name_en:i.name_en||'',category_slug:categories.find(c=>c.id===i.category_id)?.slug||'',price:i.price,available:i.available,featured:i.featured,sort_order:i.sort_order,image_url:i.image_url||''}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Menu');XLSX.writeFile(wb,`menu-${new Date().toISOString().slice(0,10)}.xlsx`)};
$("#importMenuFile").onchange=async e=>{try{const file=e.target.files[0];if(!file)return;let rows=[];if(file.name.toLowerCase().endsWith('.json')){const obj=JSON.parse(await file.text());rows=obj.menu_items||obj}else{const wb=XLSX.read(await file.arrayBuffer());rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]])}if(!Array.isArray(rows))throw new Error('รูปแบบไฟล์ไม่ถูกต้อง');if(!confirm(`นำเข้า ${rows.length} เมนู? รายการชื่อซ้ำอาจเพิ่มซ้ำ`))return;for(const r of rows){let category_id=r.category_id; if(!category_id&&r.category_slug)category_id=categories.find(c=>c.slug===r.category_slug)?.id; if(!category_id)category_id=categories[0]?.id;if(!category_id)throw new Error('กรุณาสร้างหมวดอาหารก่อน');const payload={name_lo:r.name_lo||r.name_th||r.name_en||'Menu',name_th:r.name_th||null,name_en:r.name_en||null,category_id,price:Number(r.price||0),available:r.available!==false&&String(r.available).toLowerCase()!=='false',featured:r.featured===true||String(r.featured).toLowerCase()==='true',sort_order:Number(r.sort_order||999),image_url:r.image_url||null,variants:Array.isArray(r.variants)?r.variants:[]};const {error}=await client.from('menu_items').insert(payload);if(error)throw error}alert('นำเข้าสำเร็จ');await loadMenus()}catch(err){alert(err.message)}finally{e.target.value=''}};

function updateStats(){$("#statMenu").textContent=menuItems.length;$("#statAvailable").textContent=menuItems.filter(i=>i.available).length;$("#statFeatured").textContent=menuItems.filter(i=>i.featured).length;$("#statBookings").textContent=bookings.length}
checkSession();
