'use strict';
const cfg=window.TPG_CONFIG,$=s=>document.querySelector(s),money=n=>`${Math.round(Number(n||0)).toLocaleString()} ກີບ`;
let client=null,user=null,orders=[],payments=[],items=[];
const configured=()=>cfg?.SUPABASE_URL?.startsWith('https://')&&!String(cfg?.SUPABASE_ANON_KEY||'').includes('PASTE_');
if(configured())client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);else $('#loginStatus').textContent='กรุณาตรวจ config.js';
function isoDate(d){return d.toISOString().slice(0,10)}function localStart(v){return new Date(v+'T00:00:00').toISOString()}function localEnd(v){return new Date(v+'T23:59:59.999').toISOString()}
function setToday(){const d=new Date();$('#dateFrom').value=$('#dateTo').value=isoDate(d)}function setMonth(){const d=new Date();$('#dateFrom').value=isoDate(new Date(d.getFullYear(),d.getMonth(),1));$('#dateTo').value=isoDate(d)}
setMonth();$('#todayBtn').onclick=()=>{setToday();loadReport()};$('#monthBtn').onclick=()=>{setMonth();loadReport()};
async function enter(u){user=u;$('#login').hidden=true;$('#app').hidden=false;$('#logout').hidden=false;$('#userEmail').textContent=u.email||'';await loadReport()}
async function init(){if(!client)return;const {data}=await client.auth.getSession();if(data.session)await enter(data.session.user)}
$('#loginBtn').onclick=async()=>{const {data,error}=await client.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)$('#loginStatus').textContent=error.message;else enter(data.user)};$('#logout').onclick=async()=>{await client.auth.signOut();location.reload()};
async function loadReport(){try{const from=$('#dateFrom').value,to=$('#dateTo').value;if(!from||!to)throw new Error('กรุณาเลือกวันที่');let q=client.from('orders').select('*').eq('status','paid').gte('closed_at',localStart(from)).lte('closed_at',localEnd(to)).order('closed_at',{ascending:false}).limit(5000);const bill=$('#billSearch').value.trim(),table=$('#tableSearch').value;if(bill)q=q.ilike('order_number',`%${bill}%`);if(table)q=q.eq('table_number',Number(table));const {data,error}=await q;if(error)throw error;orders=data||[];const ids=orders.map(o=>o.id);payments=[];items=[];if(ids.length){for(let i=0;i<ids.length;i+=200){const batch=ids.slice(i,i+200);const [p,it]=await Promise.all([client.from('payments').select('*').in('order_id',batch),client.from('order_items').select('*').in('order_id',batch)]);if(p.error)throw p.error;if(it.error)throw it.error;payments.push(...(p.data||[]));items.push(...(it.data||[]))}}render()}catch(e){alert(e.message||e);console.error(e)}}
$('#loadBtn').onclick=loadReport;$('#billSearch').onkeydown=e=>{if(e.key==='Enter')loadReport()};$('#tableSearch').onkeydown=e=>{if(e.key==='Enter')loadReport()};
function render(){const sales=orders.reduce((s,o)=>s+Number(o.grand_total||0),0),vat=orders.reduce((s,o)=>s+Number(o.vat_amount||0),0),discount=orders.reduce((s,o)=>s+Number(o.discount||0),0);$('#sales').textContent=money(sales);$('#bills').textContent=orders.length.toLocaleString();$('#vat').textContent=money(vat);$('#discount').textContent=money(discount);$('#average').textContent=money(orders.length?sales/orders.length:0);const pm={};payments.forEach(p=>pm[p.method]=(pm[p.method]||0)+Number(p.amount||0));$('#payments').innerHTML=Object.entries(pm).length?Object.entries(pm).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="metric-row"><span>${k}</span><b>${money(v)}</b></div>`).join(''):'<p class="empty">No payment data</p>';const top={};items.forEach(x=>{const k=x.item_name||'Unknown';top[k]??={qty:0,total:0};top[k].qty+=Number(x.quantity||0);top[k].total+=Number(x.line_total||Number(x.unit_price||0)*Number(x.quantity||0))});$('#topMenu').innerHTML=Object.entries(top).sort((a,b)=>b[1].qty-a[1].qty).slice(0,10).map(([k,v])=>`<div class="metric-row"><span>${k} (${v.qty})</span><b>${money(v.total)}</b></div>`).join('')||'<p class="empty">No menu data</p>';const payByOrder={};payments.forEach(p=>payByOrder[p.order_id]=p.method);$('#rows').innerHTML=orders.map(o=>`<tr><td>${new Date(o.closed_at||o.created_at).toLocaleString()}</td><td>${o.order_number}</td><td>${o.table_number||'Takeaway'}</td><td>${money(o.subtotal)}</td><td>${money(o.discount)}</td><td>${money(o.vat_amount)}</td><td><b>${money(o.grand_total)}</b></td><td>${payByOrder[o.id]||'-'}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">ไม่พบข้อมูล</td></tr>';$('#resultInfo').textContent=`${orders.length.toLocaleString()} bills • limit 5,000`}
function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#exportCsv').onclick=()=>{const pay={};payments.forEach(p=>pay[p.order_id]=p.method);const rows=[['date','bill','table','subtotal','discount','vat','total','payment'],...orders.map(o=>[o.closed_at,o.order_number,o.table_number||'Takeaway',o.subtotal,o.discount,o.vat_amount,o.grand_total,pay[o.id]||''])];download(`tum-pa-guay-sales-${$('#dateFrom').value}-to-${$('#dateTo').value}.csv`,rows.map(r=>r.map(csvEscape).join(',')).join('\n'),'text/csv;charset=utf-8')};
$('#backupJson').onclick=()=>download(`tum-pa-guay-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:'8.0.0',exported_at:new Date().toISOString(),filters:{from:$('#dateFrom').value,to:$('#dateTo').value},orders,payments,order_items:items},null,2),'application/json');
init();
