const $=s=>document.querySelector(s);
const PROFILE_KEY='restaurant_template_profiles',ACTIVE_KEY='restaurant_template_active_profile';
let step=1,client=null,user=null,editingId=null,currentLogoUrl='',connectionOk=false;
function uid(){return crypto.randomUUID?crypto.randomUUID():`r-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function profiles(){try{const x=JSON.parse(localStorage.getItem(PROFILE_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveProfiles(items){localStorage.setItem(PROFILE_KEY,JSON.stringify(items))}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setMessage(text,type='error'){const el=$('#message');el.textContent=text||'';el.className=type}
function activeProfile(){const id=localStorage.getItem(ACTIVE_KEY);return profiles().find(x=>x.id===id)||null}
function updateActiveStatus(){const p=activeProfile();$('#activeStatus').textContent=p?`กำลังใช้งาน: ${p.profileName}`:'ยังไม่ได้เลือกร้าน';$('#openActive').disabled=!p}
function renderProfiles(){const items=profiles(),active=localStorage.getItem(ACTIVE_KEY);$('#profileCount').textContent=`${items.length} ร้าน`;$('#profileList').innerHTML=items.length?items.map(p=>`<article class="profile-card ${p.id===active?'active':''}"><button class="profile-main" data-action="activate" data-id="${p.id}"><b>${esc(p.profileName||p.RESTAURANT?.nameLao||'Restaurant')}</b><small>${esc(p.RESTAURANT?.nameLao||p.RESTAURANT?.nameThai||'ยังไม่มีชื่อร้าน')}</small><em>${p.id===active?'● กำลังใช้งาน':'เลือกใช้งาน'}</em></button><div><button data-action="edit" data-id="${p.id}">แก้ไข</button><button data-action="delete" data-id="${p.id}" class="danger">ลบ</button></div></article>`).join(''):'<div class="empty">ยังไม่มีร้าน<br>กด “เพิ่มร้านใหม่” เพื่อเริ่มต้น</div>';document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleProfileAction(b.dataset.action,b.dataset.id));updateActiveStatus()}
function handleProfileAction(action,id){if(action==='activate')return activateProfile(id,true);if(action==='edit')return loadProfile(id,true);if(action==='delete')return deleteProfile(id)}
function activateProfile(id,notify=false){const p=profiles().find(x=>x.id===id);if(!p)return;localStorage.setItem(ACTIVE_KEY,id);renderProfiles();if(notify)setMessage(`✓ เปลี่ยนเป็นร้าน “${p.profileName}” แล้ว หน้า Website/Admin/POS จะใช้ร้านนี้เมื่อเปิดหรือรีเฟรชหน้า`,'success')}
function deleteProfile(id){const p=profiles().find(x=>x.id===id);if(!p||!confirm(`ลบรายชื่อร้าน “${p.profileName}” ออกจาก Browser เครื่องนี้หรือไม่?\nข้อมูลใน Supabase จะไม่ถูกลบ`))return;saveProfiles(profiles().filter(x=>x.id!==id));if(localStorage.getItem(ACTIVE_KEY)===id){const first=profiles()[0];first?localStorage.setItem(ACTIVE_KEY,first.id):localStorage.removeItem(ACTIVE_KEY)}if(editingId===id)newProfile();renderProfiles();setMessage('ลบรายชื่อร้านออกจากเครื่องแล้ว (ฐานข้อมูล Supabase ยังอยู่)','success')}
function fill(id,v){const el=$('#'+id);if(el&&v!==undefined&&v!==null)el.value=v}
function loadProfile(id,goStep=false){const p=profiles().find(x=>x.id===id);if(!p)return;editingId=id;client=null;connectionOk=false;currentLogoUrl=p.logoUrl||'';fill('profileName',p.profileName);fill('supabaseUrl',p.SUPABASE_URL);fill('supabaseKey',p.SUPABASE_ANON_KEY);fill('storageBucket',p.STORAGE_BUCKET||'menu-images');fill('nameLo',p.RESTAURANT?.nameLao);fill('nameTh',p.RESTAURANT?.nameThai);fill('nameEn',p.RESTAURANT?.nameEnglish);fill('phone',p.RESTAURANT?.phoneDisplay);fill('whatsapp',p.RESTAURANT?.whatsappIntl);fill('facebook',p.RESTAURANT?.facebookName);fill('maps',p.RESTAURANT?.mapsUrl);fill('addressLo',p.RESTAURANT?.addressLao);fill('language',p.DEFAULT_LANGUAGE||'lo');fill('currency',p.currency||'LAK');fill('vatMode',p.vatMode||'inclusive');fill('vatRate',p.vatRate??10);fill('primaryColor',p.primaryColor||'#0b5d3b');fill('accentColor',p.accentColor||'#d8ad56');fill('tableCount',p.tableCount||20);showLogo(currentLogoUrl);$('#modeTitle').textContent=`แก้ไข: ${p.profileName}`;activateProfile(id);if(goStep)showStep(1);setMessage('โหลดข้อมูลโปรไฟล์แล้ว กด “โหลดค่าร้านจาก Supabase” เพื่อดึงข้อมูลล่าสุด','info')}
function newProfile(){editingId=null;client=null;user=null;connectionOk=false;currentLogoUrl='';$('#wizardForm').reset();fill('storageBucket','menu-images');fill('vatRate',10);fill('tableCount',20);fill('primaryColor','#0b5d3b');fill('accentColor','#d8ad56');showLogo('');$('#modeTitle').textContent='เพิ่มร้านใหม่';$('#connectionResult').innerHTML='';$('#loginStatus').innerHTML='';setMessage('');showStep(1)}
function showStep(n){step=Math.max(1,Math.min(5,n));document.querySelectorAll('.panel').forEach(x=>x.hidden=Number(x.dataset.step)!==step);document.querySelectorAll('.steps span').forEach((x,i)=>x.classList.toggle('active',i<step));$('#prev').hidden=step===1||step===5;$('#next').hidden=step===5;$('#next').textContent=step===4?'บันทึกและตั้งเป็นร้านที่ใช้งาน':'ถัดไป';window.scrollTo({top:0,behavior:'smooth'})}
function makeClient(){const url=$('#supabaseUrl').value.trim(),key=$('#supabaseKey').value.trim();if(!/^https:\/\/.+\.supabase\.co\/?$/i.test(url))throw new Error('Project URL ไม่ถูกต้อง');if(key.length<20)throw new Error('Publishable / Anon Key ไม่ถูกต้อง');client=supabase.createClient(url,key);return client}
async function testConnection(){try{setMessage('กำลังตรวจสอบการเชื่อมต่อ…','info');makeClient();const checks=[];for(const table of ['restaurant_settings','restaurant_tables','menu_items','categories']){const {error}=await client.from(table).select('*',{count:'exact',head:true});checks.push({table,ok:!error,error:error?.message})}connectionOk=checks.every(x=>x.ok);$('#connectionResult').innerHTML=checks.map(x=>`<div class="${x.ok?'okline':'badline'}">${x.ok?'✓':'✕'} ${x.table}${x.ok?'':' — '+esc(x.error)}</div>`).join('');if(!connectionOk)throw new Error('พบตารางไม่ครบ กรุณารัน SQL ติดตั้ง/อัปเกรดให้ครบ');setMessage('✓ เชื่อมต่อสำเร็จและตรวจพบตารางสำคัญครบ','success');return true}catch(e){connectionOk=false;setMessage('เชื่อมต่อไม่สำเร็จ: '+e.message,'error');return false}}
async function loadFromDatabase(){try{if(!await testConnection())return;const {data:s,error}=await client.from('restaurant_settings').select('*').eq('id',1).maybeSingle();if(error)throw error;if(s){fill('nameLo',s.restaurant_name_lo);fill('nameTh',s.restaurant_name_th);fill('nameEn',s.restaurant_name_en);fill('phone',s.phone_display);fill('whatsapp',s.whatsapp_intl);fill('facebook',s.facebook_name);fill('maps',s.maps_url);fill('addressLo',s.address_lo);fill('language',s.default_language||'lo');fill('currency',s.currency_code||'LAK');fill('vatMode',s.vat_mode||'inclusive');fill('vatRate',s.vat_rate??10);fill('primaryColor',s.theme_primary||'#0b5d3b');fill('accentColor',s.theme_accent||'#d8ad56');currentLogoUrl=s.logo_url||'';showLogo(currentLogoUrl)}const {count,error:tErr}=await client.from('restaurant_tables').select('*',{count:'exact',head:true}).eq('active',true);if(!tErr&&count!=null)fill('tableCount',count);setMessage('✓ โหลดข้อมูลล่าสุดจาก Supabase แล้ว','success')}catch(e){setMessage('โหลดข้อมูลไม่สำเร็จ: '+e.message,'error')}}
async function ownerLogin(){try{client=client||makeClient();const email=$('#ownerEmail').value.trim(),password=$('#ownerPassword').value;if(!email||!password)throw new Error('กรอก Email และ Password');const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;$('#loginStatus').innerHTML=`<div class="okline">✓ เข้าสู่ระบบแล้ว: ${esc(user.email)}</div>`;setMessage('ตรวจสอบบัญชีเจ้าของร้านสำเร็จ','success')}catch(e){$('#loginStatus').innerHTML=`<div class="badline">✕ ${esc(e.message)}</div>`;setMessage('เข้าสู่ระบบไม่สำเร็จ: '+e.message,'error')}}
async function uploadLogo(file){if(!file)return currentLogoUrl||null;const ext=(file.name.split('.').pop()||'png').replace(/[^a-z0-9]/gi,'');const path=`branding/logo-${Date.now()}.${ext}`;const bucket=$('#storageBucket').value.trim()||'menu-images';const {error}=await client.storage.from(bucket).upload(path,file,{upsert:true,contentType:file.type||undefined});if(error)throw error;return client.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function ensureTables(count){const {data,error}=await client.from('restaurant_tables').select('*').order('table_number');if(error)throw error;let rows=data||[],active=rows.filter(x=>x.active);while(active.length<count){const inactive=rows.find(x=>!x.active);if(inactive){const {error:e}=await client.from('restaurant_tables').update({active:true,label:`ໂຕະ ${inactive.table_number}`}).eq('id',inactive.id);if(e)throw e;inactive.active=true;active.push(inactive)}else{const no=rows.reduce((m,x)=>Math.max(m,+x.table_number||0),0)+1;const {data:n,error:e}=await client.from('restaurant_tables').insert({table_number:no,label:`ໂຕະ ${no}`,capacity:4,active:true}).select().single();if(e)throw e;rows.push(n);active.push(n)}}while(active.length>count){const x=active.pop();const {error:e}=await client.from('restaurant_tables').update({active:false}).eq('id',x.id);if(e)throw e}}
async function saveAll(){try{setMessage('กำลังบันทึกข้อมูล…','info');if(!connectionOk&&!(await testConnection()))return;const logo=await uploadLogo($('#logoFile').files[0]);const db={id:1,restaurant_name_lo:$('#nameLo').value.trim()||'ຮ້ານອາຫານ',restaurant_name_th:$('#nameTh').value.trim()||'ร้านอาหาร',restaurant_name_en:$('#nameEn').value.trim()||'Restaurant',phone_display:$('#phone').value.trim(),whatsapp_intl:$('#whatsapp').value.trim(),facebook_name:$('#facebook').value.trim(),maps_url:$('#maps').value.trim(),address_lo:$('#addressLo').value.trim(),default_language:$('#language').value,currency_code:$('#currency').value,vat_mode:$('#vatMode').value,vat_rate:+$('#vatRate').value||0,theme_primary:$('#primaryColor').value,theme_accent:$('#accentColor').value,setup_completed:true,...(logo?{logo_url:logo}:{})};const {error}=await client.from('restaurant_settings').upsert(db,{onConflict:'id'});if(error)throw error;const tableCount=Math.max(1,Math.min(500,+$('#tableCount').value||20));await ensureTables(tableCount);const id=editingId||uid(),profileName=$('#profileName').value.trim()||db.restaurant_name_lo;const profile={id,profileName,SUPABASE_URL:$('#supabaseUrl').value.trim(),SUPABASE_ANON_KEY:$('#supabaseKey').value.trim(),STORAGE_BUCKET:$('#storageBucket').value.trim()||'menu-images',DEFAULT_LANGUAGE:db.default_language,currency:db.currency_code,vatMode:db.vat_mode,vatRate:db.vat_rate,primaryColor:db.theme_primary,accentColor:db.theme_accent,tableCount,logoUrl:logo||'',RESTAURANT:{nameLao:db.restaurant_name_lo,nameThai:db.restaurant_name_th,nameEnglish:db.restaurant_name_en,phoneDisplay:db.phone_display,whatsappIntl:db.whatsapp_intl,facebookName:db.facebook_name,mapsUrl:db.maps_url,addressLao:db.address_lo}};const items=profiles().filter(x=>x.id!==id);items.push(profile);saveProfiles(items);editingId=id;localStorage.setItem(ACTIVE_KEY,id);renderProfiles();$('#finishText').textContent=`ร้าน “${profileName}” ถูกบันทึกและตั้งเป็นร้านที่กำลังใช้งานแล้ว`;setMessage('✓ บันทึกสำเร็จ','success');showStep(5)}catch(e){setMessage('บันทึกไม่สำเร็จ: '+e.message,'error')}}
function showLogo(url){const img=$('#logoPreview');if(url){img.src=url;img.hidden=false;$('#logoHint').textContent='โลโก้ปัจจุบัน (เลือกไฟล์ใหม่เพื่อเปลี่ยน)'}else{img.hidden=true;img.removeAttribute('src');$('#logoHint').textContent='ยังไม่ได้เลือกโลโก้ใหม่'}}
function exportProfiles(){const safe=profiles().map(({SUPABASE_ANON_KEY,...p})=>({...p,SUPABASE_ANON_KEY:''}));const blob=new Blob([JSON.stringify({version:'2.0.1',exportedAt:new Date().toISOString(),profiles:safe},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='restaurant-profiles-v2.0.2.json';a.click();URL.revokeObjectURL(a.href);setMessage('Export รายชื่อร้านแล้ว โดยไม่ส่งออก Supabase Key','success')}
async function importProfiles(file){try{const data=JSON.parse(await file.text()),incoming=Array.isArray(data)?data:data.profiles;if(!Array.isArray(incoming))throw new Error('รูปแบบไฟล์ไม่ถูกต้อง');const items=profiles();for(const p of incoming){if(!p.profileName||!p.SUPABASE_URL)continue;items.push({...p,id:uid(),SUPABASE_ANON_KEY:p.SUPABASE_ANON_KEY||''})}saveProfiles(items);renderProfiles();setMessage('Import รายชื่อร้านแล้ว กรุณาแก้ไขแต่ละร้านและใส่ Supabase Key ใหม่','success')}catch(e){setMessage('Import ไม่สำเร็จ: '+e.message,'error')}}
$('#newProfile').onclick=newProfile;$('#testConnection').onclick=testConnection;$('#loadFromDatabase').onclick=loadFromDatabase;$('#ownerLogin').onclick=ownerLogin;$('#skipLogin').onclick=()=>{setMessage('ข้ามการตรวจบัญชี สามารถเข้าสู่ระบบภายหลังใน Admin','info');showStep(3)};$('#prev').onclick=()=>showStep(step-1);$('#next').onclick=async()=>{if(step===1){if(!$('#profileName').value.trim()||!$('#supabaseUrl').value.trim()||!$('#supabaseKey').value.trim())return setMessage('กรอกชื่อโปรไฟล์ Project URL และ Key ให้ครบ','error');if(!connectionOk&&!(await testConnection()))return}if(step<4)return showStep(step+1);await saveAll()};$('#openActive').onclick=()=>location.href='index.html';$('#editAgain').onclick=()=>showStep(1);$('#exportProfiles').onclick=exportProfiles;$('#importProfiles').onchange=e=>{if(e.target.files[0])importProfiles(e.target.files[0]);e.target.value=''};$('#logoFile').onchange=e=>{const f=e.target.files[0];if(f){const u=URL.createObjectURL(f);showLogo(u)}};
renderProfiles();const active=activeProfile();active?loadProfile(active.id):newProfile();
